### ISSUE TITLE
Add option to specify min_samples_leaf and min_samples_split

### ISSUE THREAD

**Issue by Samreay** [evevkovacs/ML-SN-Classifier#3]
Hey Eve,

We've been noticing crazy overfitting when running on training datasets that isnt present in other classifiers. I believe this is because the default tree growth from sklearn will essentially have huge depth such that training can drill down to the leaf node and find the original sample, giving perfect predictions.

To test the impact of this, it would be good if we could pass in `min_samples_split` and `min_samples_split` to control how often the nodes split and the minimum number of events per node to stop single-event nodes from forming.

Would this be possible to do? Doco for convenience: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

And attached are the PR plots for train + test respectively. 

![PippinPlot4](https://user-images.githubusercontent.com/6748505/73717502-b9a3a500-4765-11ea-8c06-b676fa67223b.png)
![PippinPlot8](https://user-images.githubusercontent.com/6748505/73717503-ba3c3b80-4765-11ea-9e53-d807952e490d.png)

**Comment by evevkovacs** [comment]
Yes it would be possible to add these as options. I can do this in the next day or so. What is the composition and size of the training set that you are using?

**Comment by Samreay** [comment]
Composition for training is G10 sims + half of Marias templates. Large sims (the same ones being used for SNN), which have approx ~1mil events, so around 100k events in the FITRES file I believe.

**Comment by rmorgan10** [comment]
On the topic of adding options, perhaps one of the tweak-able options, could be the `max_depth` of the trees in the ensemble?

**Comment by evevkovacs** [comment]
I have added the requested options and pushed them to master

**Comment by Samreay** [comment]
Thanks Eve, Ill integrate these right now :)
